export const siteConfig = {
  name: 'موسسه یاوران سلامت روان',
  shortName: 'یاوران سلامت روان',
  nameEn: 'Yavaran-e Salamat-e Ravan',
  url: 'https://rohanian-ysr.ir',
  description:
    'موسسه آموزشی و پژوهشی یاوران سلامت روان در قم؛ ارائه‌دهنده دوره‌های تخصصی روانشناسی، مشاوره خانواده، روان‌درمانی شناختی-رفتاری و روانشناسی اسلامی بر پایه پیوند دانش نوین و معارف اسلامی با گواهی معتبر.',
  ogTitle: 'موسسه یاوران سلامت روان | مشاوره و آموزش تخصصی روانشناسی در قم',
  keywords: [
    'روانشناسی',
    'مشاوره روانشناسی',
    'روان‌درمانی',
    'مشاوره خانواده',
    'روانشناسی اسلامی',
    'روانشناسی معنوی',
    'سلامت روان',
    'دوره آموزش روانشناسی',
    'مشاور در قم',
    'روانشناس در قم',
    'آموزش تخصصی روانشناسی',
    'مهارت‌های زندگی',
    'تربیت فرزند',
    'یاوران سلامت روان',
  ],
  phone: '۰۹۰۵ ۰۷۹ ۵۷۵۴',
  phoneE164: '+989050795754',
  email: 'psy.rohanian@gmail.com',
  address: 'قم، بلوار امین، بین امین ۲۵ و امین ۲۷ (محله بلوار امین و ساحلی)',
  addressLocality: 'قم',
  addressRegion: 'قم',
  addressCountry: 'IR',
  geo: {
    latitude: 34.624129311403216,
    longitude: 50.85267917324583,
  },
  sameAs: [
    'https://www.instagram.com/rohanian.psychologist93',
    'https://eitaa.com/rohanian_psychologist93',
  ],
  mapEmbed:
    'https://neshan.org/maps/iframe/places/c5ec86f9a77e77dbcac9ab9cfab4a252#c34.624-50.853-20z-0p/34.624129311403216/50.85267917324583',
  openingHours: 'شنبه تا چهارشنبه، ۹ تا ۱۸',
} as const